<?php

    include('password/head.html');
    
//////////////////////////////////////// MESSAGE D'ERREUR ///////////////////////////////////

?>
    <body>
        <main>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Une erreur s'est produite :-(<img id="logo" src="../img/toucan_yoann_sans_aile.png" alt="mascotte toucan" /></h1>
                    </div>
                    <div class="col-sm-12 center">
                        <form action="../Kids.phtml">
                            <button type="submit" class="btn">Retourner sur Melisme</button>
                        </form>
                    </div>
                </div>
            </div>
        </main>
    </body>
    </html>