<?php
$pdo = new PDO('mysql:host=localhost;dbname=melismekids;port=3306', 'root', 'root');
$pdo->exec('SET NAMES UTF8');

$token = $_GET['token'];
$Contact = $_GET['email'];

$query = $pdo->prepare
(
    "SELECT * FROM newpassword where Token = ?"
);
$query->execute([$_GET['token']]);

include('head.html');

if($user = $query->fetch())
{ 
  
?>
<body>
    <main>
        <div class="container">
        <div class="row">
        <div class="col-sm-12">
        <h1>Nouveau mot de passe<img id="logo" src="../img/toucan_yoann_sans_aile.png" alt="mascotte toucan" /></h1>
        </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 formulaire">
            <p class="text-center">Entrez votre nouveau mot de passe</p>
            <div id="mdp_verification"></div>
            <form method="POST" id="passwordForm">
                <input type="password" pattern=".{5,100}" class="input-lg form-control" name="password1" id="password1" placeholder="Nouveau Mot de passe" autocomplete="off" required>
                <div class="row">
                    <div class="col-sm-6">
                        <span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 5 Lettres Minimum<br>
                    </div>
                </div>
                <input type="password" class="input-lg form-control" name="password2" id="password2" placeholder="Répéter le Mot de passe" autocomplete="off" required>
                <div class="row">
                <div class="col-sm-12">
                <span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Compatibilité des Mots de passe
                </div>
                </div>
                <input name="Contact" type="hidden" value="<?=$Contact?>">
                <input name="token" type="hidden" value="<?=$token?>">

                <input id="changemdp_button" type="submit" pattern=".{5,100}" class="col-xs-12 btn btn-primary btn-load btn-lg" data-loading-text="Changing Password..." value="Changer de Mot de passe">
            </form>
            <form action="../Kids.phtml" id="melisme_form" style="display: none">
                   <br> <button type="submit" class="col-xs-12 btn btn-primary btn-load btn-lg">Retourner sur Melisme</button>
            </form>
            </div><!--/col-sm-6-->
            </div><!--/row-->
        </div>
    </main>
</body>
</html>
<script src="../js/password.js"></script>
<?php
}
else
    {
        header('Location: error.phtml');
    }
?>