<!DOCTYPE html>

<html lang="fr">
<head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="../img/toucan_yoann_avec_aile.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Melisme KID'S</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Gorditas:wght@400;700&display=swap" rel="stylesheet">

<!-- JS -->
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="https://kit.fontawesome.com/ef488c0f83.js" crossorigin="anonymous"></script>

<!-- BOOTSTRAP -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!-- CSS -->

    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/KidsStyle.css">
    <link rel="stylesheet" href="css/style.css">

</head>
<body>
    <main>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Une erreur s'est produite :-(<img id="logo" src="img/toucan_yoann_sans_aile.png" alt="mascotte toucan" /></h1>
                </div>
                <div class="col-sm-12 center">
                    <form action="Kids.phtml">
                        <button type="submit" class="btn">Retourner sur Melisme</button>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <section>

            <!-- Début Footer -->

            <article class="FooterMelisme">
                <h3>Melisme KID'S</h3>
                <a href="#">Home</a>
                <a href="#">Jouer</a>
                <a href="#">About Us</a>
            </article>

            <article class="Footerenplus">
                <h3>En plus</h3>
                <div id="img_src">
                    <div>
                        <button id="show">Show Attribution</button>
                        <button id="hide">Hide Attribution</button>
                    </div>
                </div>
                <div>
                    <div id="links">
                        - <a href="https://fr.vecteezy.com/vecteur-libre/music">Music Vecteurs par Vecteezy</a><br>
                        - <a href="https://fr.vecteezy.com/vecteur-libre/illustration">Illustration Vecteurs par
                            Vecteezy</a>
                    </div>
                </div>
            </article>

            <article class="verifier">
                <a href="#">
                    <img id="toucan4" src="../Kids/img/toucan_yoann_blanc_avec_aile.png" alt="mascotte toucan" />
                </a>
            </article>

            <article class="Contact">
                <h3>Contact</h3>
                <div class="Footericone">
                    <a href="#"><i class="fas fa-phone-alt"></i></a>
                    <a href="#"><i class="fas fa-envelope"></i></a>
                    <a href="#"><i class="fas fa-question"></i></a>
                </div>
            </article>

            <article class="footersocial">
                <i id="globe" class="fas fa-globe"></i>
                <select name="Language">
                    <option value="Francais">Français</option>
                    <option value="English">English</option>
                </select>
                <div class="social">
                    <a href="#"><i class="fab fa-facebook-square"></i></a>
                    <a href="#"><i class="fab fa-twitter-square"></i></a>
                    <a href="#"><i class="fab fa-instagram-square"></i></a>
                </div>
            </article>

            <!-- Fin Footer -->

        </section>
    </footer>
    <!-- JS -->
        <script src="js/ajax.js"></script>
        <script src="js/Kids.js"></script>
</body>
</html>