<!doctype html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <title>Melisme KID'S</title>
    <link rel="shortcut icon" href="../img/toucan_yoann_avec_aile.png">
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Gorditas:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">
   
      <!--CSS -->
      <link rel="stylesheet" href="../css/normalize.css">
      <link rel="stylesheet" href="style.css">

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- JS -->
    <script src="https://kit.fontawesome.com/ef488c0f83.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>

</head>
<body>
  	<main>
        <section>
            <h1 style="letter-spacing: -10px;">

                <input id="button" onclick="location.href='../Kids.phtml';" class="favorite styled" type="button" value="Accueil">
                <span class="nowrap">
                    <span style="color: #D03131;">K</span>
                    <span style="color: #C60001;">i</span>
                    <span style="color: #69A7D0;">D</span>
                    <span style="color: #056CB1;">'</span>
                    <span style="color: #FEE8A2; margin-right: 30px;">S</span>
                </span>

                <span class="nowrap">
                    <span style="color: #FFC81B;" >Q</span>
                    <span style="color: #90C796;" >U</span>
                    <span style="color: #3C9C45;" >I</span>
                    <span style="color: #FF8A9A;" >Z</span>
                </span>
                <img class="lion" src="../img/lion_yoann2.png" alt="lion" />
                
              </h1>

            <article id="all-quizz-container">
                <div class="quiz-container">
                    <div id="quiz"></div>
                    <div class="buttons">
                        <input type="button" class="btn btn-info" id="previous" value="Question précédente"></input>
                        <input type="button" class="btn btn-info" id="next" value="Question suivante"></input>
                        <input type="button" class="btn btn-success" id="submit" value="Vérifier les réponses"></input>
                        <div id="results"></div>
                    </div>
                  </div>
                
                 
            </article>
              
            
        </section>
  	</main>
      <footer>
        <section>
            
<!-- Début Footer -->

            <article class="FooterMelisme">
                <h3>Melisme KID'S</h3>
                <a href="#">Home</a>
                <a href="#">Jouer</a>
                <a href="#">About Us</a>    
            </article>

            <article class="Footerenplus">
                <h3>En plus</h3>
                <div id="img_src">
                    <div>
                        <button id="show">Show Attribution</button>
                        <button id="hide">Hide Attribution</button>
                    </div>
                </div>
                <div>
                    <div id="links">
                        - <a href="https://fr.vecteezy.com/vecteur-libre/music">Music Vecteurs par Vecteezy</a><br>
                        - <a href="https://fr.vecteezy.com/vecteur-libre/illustration">Illustration Vecteurs par Vecteezy</a>
                    </div>
                </div>
            </article>

            <article class="verifier">
                <a href="#">
                    <img  id="toucan4" src="../img/toucan_yoann_blanc_avec_aile.png" alt="mascotte toucan"/>
                </a>
            </article>

            <article class="Contact">
                <h3>Contact</h3>
                <div class="Footericone">
                    <a href="#"><i class="fas fa-phone-alt"></i></a>
                    <a href="#"><i class="fas fa-envelope"></i></a>
                    <a href="#"><i class="fas fa-question"></i></a>
                </div>
            </article>

            <article class="footersocial">
                <i id="globe" class="fas fa-globe"></i>
                <select name="Language">
                    <option value="Francais">Français</option>
                    <option value="English">English</option>
                </select>
                <div class="social">
                    <a href="#"><i class="fab fa-facebook-square"></i></a>
                    <a href="#"><i class="fab fa-twitter-square"></i></a>
                    <a href="#"><i class="fab fa-instagram-square"></i></a>
                </div>
            </article>    
            
<!-- Fin Footer -->

        </section>
    </footer>
</body>
<script src="../js/Kids.js"></script>
<script src="script.js"></script>


</html>