<!doctype html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <title>Melisme KID'S</title>
    <link rel="shortcut icon" href="../img/toucan_yoann_avec_aile.png">
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Gorditas:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">
   
      <!--CSS -->
      <link rel="stylesheet" href="../css/normalize.css">
      <link rel="stylesheet" href="style.css">

  

    <!-- JS -->
    <script src="https://kit.fontawesome.com/ef488c0f83.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  

</head>
<body>
    <main>

      <section> 

        <h1 style="letter-spacing: -10px;">

          <input id="button" onclick="location.href='../Kids.phtml';" class="favorite styled" type="button" value="Accueil">

          <span style="color: #D03131;" >K</span>
          <span style="color: #C60001;" >i</span>
          <span style="color: #69A7D0;" >D</span>
          <span style="color: #056CB1;" >'</span>
          <span style="color: #FEE8A2; margin-right: 30px;" >S</span> 

          <span style="color: #FFC81B;" >P</span>
          <span style="color: #90C796;" >I</span>
          <span style="color: #3C9C45;" >A</span>
          <span style="color: #FF8A9A;" >N</span>
          <span style="color: #FF7185;" >O</span>
          <img class="croco" src="../img/croco_yoann2.png" alt="crocodile" /> 
        </h1>

        <article id="black_legend">
          <div class="schema_un">
            <div style="margin-left: 75px;">
              a
            </div>
            <div style="margin-left: 68px;">
              z
            </div>
          </div>

          <div class="schema_deux">
            <div style="margin-left: 148px;">
              e
            </div>
            <div style="margin-left: 68px;">
              r
            </div>
            <div style="margin-left: 68px;">
              t
            </div>
          </div>

          <div class="schema_trois">
            <div style="margin-left: 148px;">
              y
            </div>
            <div  style="margin-left: 68px;">
              u
            </div>
          </div>

          <div class="schema_quatre">
            <div style="margin-left: 153px;">
              i
            </div>
            <div style="margin-left: 70px;">
              o
            </div>
            <div style="margin-left: 70px;">
              p
            </div>
          </div>
        </article>

        <article class="piano">

          <div class="key_div">
            <div data-note="a" class="key white"></div>
            <p class="key_p">q</p>
          </div>
          
          <div data-note="b" class="key black"></div>
          <div class="key_div">
            <div data-note="c" class="key white"></div>
            <p class="key_p">w</p>
          </div>

          <div data-note="d" class="key black"></div>
          <div class="key_div">
            <div data-note="e" class="key white"></div>
            <p class="key_p">s</p>
          </div>
          <div class="key_div">
            <div data-note="f" class="key white"></div>
            <p class="key_p">x</p>
          </div>

          <div data-note="g" class="key black"></div>
          <div class="key_div">
            <div data-note="h" class="key white"></div>
            <p class="key_p">d</p>
          </div>

          <div data-note="i" class="key black"></div>
          <div class="key_div">
            <div data-note="j" class="key white"></div>
            <p class="key_p">c</p>
          </div>
          
          <div data-note="k" class="key black"></div>
          <div class="key_div">
            <div data-note="l" class="key white"></div>
            <p class="key_p">f</p>
          </div>
          <div class="key_div">
            <div data-note="m" class="key white"></div>
            <p class="key_p">v</p>
          </div>

          <div data-note="n" class="key black"></div>
          <div class="key_div">
            <div data-note="o" class="key white"></div>
            <p class="key_p">g</p>
          </div>

          <div data-note="p" class="key black"></div>
          <div class="key_div">
            <div data-note="q" class="key white"></div>
            <p class="key_p">b</p>
          </div>
          <div class="key_div">
            <div data-note="r" class="key white"></div>
            <p class="key_p">h</p>
          </div>

          <div data-note="s" class="key black"></div>
          <div class="key_div">
            <div data-note="t" class="key white"></div>
            <p class="key_p">n</p>
          </div>

          <div data-note="u" class="key black"></div>
          <div class="key_div">
            <div data-note="v" class="key white"></div>
            <p class="key_p">j</p>
          </div>

          <div data-note="w" class="key black"></div>
          <div class="key_div">
            <div data-note="x" class="key white"></div>
            <p class="key_p">,</p>
          </div>
        </article>
      
          <audio id="x" src="notes/key24.mp3"></audio>
          <audio id="w" src="notes/key23.mp3"></audio>
          <audio id="v" src="notes/key22.mp3"></audio>
          <audio id="u" src="notes/key21.mp3"></audio>
          <audio id="t" src="notes/key20.mp3"></audio>
          <audio id="s" src="notes/key19.mp3"></audio>
          <audio id="r" src="notes/key18.mp3"></audio>
          <audio id="q" src="notes/key17.mp3"></audio>
          <audio id="p" src="notes/key16.mp3"></audio>
          <audio id="o" src="notes/key15.mp3"></audio>
          <audio id="n" src="notes/key14.mp3"></audio>
          <audio id="m" src="notes/key13.mp3"></audio>

          <audio id="l" src="notes/key12.mp3"></audio>
          <audio id="k" src="notes/key11.mp3"></audio>
          <audio id="j" src="notes/key10.mp3"></audio>
          <audio id="i" src="notes/key09.mp3"></audio>
          <audio id="h" src="notes/key08.mp3"></audio>
          <audio id="g" src="notes/key07.mp3"></audio>
          <audio id="f" src="notes/key06.mp3"></audio>
          <audio id="e" src="notes/key05.mp3"></audio>
          <audio id="d" src="notes/key04.mp3"></audio>
          <audio id="c" src="notes/key03.mp3"></audio>
          <audio id="b" src="notes/key02.mp3"></audio>
          <audio id="a" src="notes/key01.mp3"></audio>
      </section>

      <section id="text">
        <h2>Utilise ton clavier</h2>
      </section>

      <section id="text_2">
        <h2>Ce jeu n'est disponible que sur ordinateur</h2>
      </section>
      
    </main>
<script src="script.js"></script>
</body>
</html>
